### ISSUE TITLE
After changing anything it jumps to the top

### ISSUE THREAD

**Issue by KulaGGin** [ReClassNET/ReClass.NET#164]
Compiled in Release configuration from a commit dc723706bb8a3e38a67cec5f610727a87598c5f7 in Visual Studio 2019. Now when I change anything in a class in x86 version, it jumps back to the top. Here's my Reclass project and Reclass itself:
[AssaultCube.zip](https://github.com/ReClassNET/ReClass.NET/files/4977548/AssaultCube.zip)
[ReClass.NET.zip](https://github.com/ReClassNET/ReClass.NET/files/4977547/ReClass.NET.zip)

And a video how it looks: https://www.youtube.com/watch?v=KHhrABKtKLs

**Comment by KulaGGin** [comment]
Just tried an older build from the b89bbfd commit and it doesn't happen there on x86 version.

**Comment by KN4CK3R** [comment]
I have tried multiple node types but can't reproduce your error. Even with your compiled file I don't get the error. Do you still have the problem?

**Comment by dhanax26** [comment]
Well i can confirm this is true, i builded the latest repository update and it happends, when you scroll down or you change/add something like more padding or change value types it scroll up to top, sometimes you can't scroll down alot cause it will return you to the top.

**Comment by KN4CK3R** [comment]
What OS do you use? I have tested Windows 7 and the latest Windows 10 update.

**Comment by KulaGGin** [comment]
I use this one:
![winver_EvI9vPngD0](https://user-images.githubusercontent.com/16989713/89509797-6bd12d80-d7d8-11ea-94f7-e7823102fb1a.png)

**Comment by dhanax26** [comment]
Hello @KN4CK3R Here's a video to show you how and when it happends, the bug only happend for me on x86 version, x64 is fine.

https://www.youtube.com/watch?v=_Xf3yju4I60

**Comment by KN4CK3R** [comment]
Ok, but that doesn't look like the error in the first video. It just scrolls on top when you are scrolling? In the first video the scrolling occurs after chaning a node.

**Comment by dhanax26** [comment]
> Ok, but that doesn't look like the error in the first video. It just scrolls on top when you are scrolling? In the first video the scrolling occurs after chaning a node.

It does the same thing of the first video if you add/change something when you have some padding added not only with scroll.

**Comment by KN4CK3R** [comment]
I can reproduce it now! Looking for fix now.

**Comment by KN4CK3R** [comment]
Debugging was a little bit painful because it stopped being reproducable for me. Please test with the latest commit. It should be fixed now.

**Comment by dhanax26** [comment]
> Debugging was a little bit painful because it stopped being reproducable for me. Please test with the latest commit. It should be fixed now.

I can confirm its fixed right now with the last commit, thank you for your time and effort!

**Comment by dpvdberg** [comment]
Seems this issue was re-introduced, as it still happens for me with the latest commit
